// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: envelope.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GamePackets {

  /// <summary>Holder for reflection information generated from envelope.proto</summary>
  public static partial class EnvelopeReflection {

    #region Descriptor
    /// <summary>File descriptor for envelope.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnvelopeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5lbnZlbG9wZS5wcm90bxIEV2lyZRoMY29tbW9uLnByb3RvGgphdXRoLnBy",
            "b3RvGgpjaGF0LnByb3RvIpcCCghFbnZlbG9wZRINCgVyZXFJZBgBIAEoBBIK",
            "CgJ0cxgCIAEoBBILCgN2ZXIYAyABKA0SIQoGcmVzdWx0GAogASgLMhEuQ29t",
            "bW9uLkVycm9ySW5mbxIjCglsb2dpbl9yZXEYZCABKAsyDi5BdXRoLkxvZ2lu",
            "UmVxSAASIwoJbG9naW5fcmVzGGUgASgLMg4uQXV0aC5Mb2dpblJlc0gAEiQK",
            "BmhzX3JlcRhuIAEoCzISLkF1dGguSGFuZHNoYWtlUmVxSAASJAoGaHNfcmVz",
            "GG8gASgLMhIuQXV0aC5IYW5kc2hha2VSZXNIABIiCghjaGF0X2V2dBjIASAB",
            "KAsyDS5DaGF0LkNoYXRNc2dIAEIGCgRib2R5Qg6qAgtHYW1lUGFja2V0c2IG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::GamePackets.CommonReflection.Descriptor, global::GamePackets.Auth.AuthReflection.Descriptor, global::GamePackets.Chat.ChatReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GamePackets.Envelope), global::GamePackets.Envelope.Parser, new[]{ "ReqId", "Ts", "Ver", "Result", "LoginReq", "LoginRes", "HsReq", "HsRes", "ChatEvt" }, new[]{ "Body" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Envelope : pb::IMessage<Envelope>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Envelope> _parser = new pb::MessageParser<Envelope>(() => new Envelope());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Envelope> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GamePackets.EnvelopeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Envelope() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Envelope(Envelope other) : this() {
      reqId_ = other.reqId_;
      ts_ = other.ts_;
      ver_ = other.ver_;
      result_ = other.result_ != null ? other.result_.Clone() : null;
      switch (other.BodyCase) {
        case BodyOneofCase.LoginReq:
          LoginReq = other.LoginReq.Clone();
          break;
        case BodyOneofCase.LoginRes:
          LoginRes = other.LoginRes.Clone();
          break;
        case BodyOneofCase.HsReq:
          HsReq = other.HsReq.Clone();
          break;
        case BodyOneofCase.HsRes:
          HsRes = other.HsRes.Clone();
          break;
        case BodyOneofCase.ChatEvt:
          ChatEvt = other.ChatEvt.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Envelope Clone() {
      return new Envelope(this);
    }

    /// <summary>Field number for the "reqId" field.</summary>
    public const int ReqIdFieldNumber = 1;
    private ulong reqId_;
    /// <summary>
    /// 요청-응답 매칭용(클라가 채워 보냄)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ReqId {
      get { return reqId_; }
      set {
        reqId_ = value;
      }
    }

    /// <summary>Field number for the "ts" field.</summary>
    public const int TsFieldNumber = 2;
    private ulong ts_;
    /// <summary>
    /// 선택: 클라 송신 시각(ms)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Ts {
      get { return ts_; }
      set {
        ts_ = value;
      }
    }

    /// <summary>Field number for the "ver" field.</summary>
    public const int VerFieldNumber = 3;
    private uint ver_;
    /// <summary>
    /// 선택: 프로토콜 대버전
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Ver {
      get { return ver_; }
      set {
        ver_ = value;
      }
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 10;
    private global::GamePackets.ErrorInfo result_;
    /// <summary>
    /// 서버→클라 응답 공통 결과(요청일 땐 비움/무시)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GamePackets.ErrorInfo Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "login_req" field.</summary>
    public const int LoginReqFieldNumber = 100;
    /// <summary>
    /// auth
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GamePackets.Auth.LoginReq LoginReq {
      get { return bodyCase_ == BodyOneofCase.LoginReq ? (global::GamePackets.Auth.LoginReq) body_ : null; }
      set {
        body_ = value;
        bodyCase_ = value == null ? BodyOneofCase.None : BodyOneofCase.LoginReq;
      }
    }

    /// <summary>Field number for the "login_res" field.</summary>
    public const int LoginResFieldNumber = 101;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GamePackets.Auth.LoginRes LoginRes {
      get { return bodyCase_ == BodyOneofCase.LoginRes ? (global::GamePackets.Auth.LoginRes) body_ : null; }
      set {
        body_ = value;
        bodyCase_ = value == null ? BodyOneofCase.None : BodyOneofCase.LoginRes;
      }
    }

    /// <summary>Field number for the "hs_req" field.</summary>
    public const int HsReqFieldNumber = 110;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GamePackets.Auth.HandshakeReq HsReq {
      get { return bodyCase_ == BodyOneofCase.HsReq ? (global::GamePackets.Auth.HandshakeReq) body_ : null; }
      set {
        body_ = value;
        bodyCase_ = value == null ? BodyOneofCase.None : BodyOneofCase.HsReq;
      }
    }

    /// <summary>Field number for the "hs_res" field.</summary>
    public const int HsResFieldNumber = 111;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GamePackets.Auth.HandshakeRes HsRes {
      get { return bodyCase_ == BodyOneofCase.HsRes ? (global::GamePackets.Auth.HandshakeRes) body_ : null; }
      set {
        body_ = value;
        bodyCase_ = value == null ? BodyOneofCase.None : BodyOneofCase.HsRes;
      }
    }

    /// <summary>Field number for the "chat_evt" field.</summary>
    public const int ChatEvtFieldNumber = 200;
    /// <summary>
    /// chat (예: 서버 푸시 이벤트)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GamePackets.Chat.ChatMsg ChatEvt {
      get { return bodyCase_ == BodyOneofCase.ChatEvt ? (global::GamePackets.Chat.ChatMsg) body_ : null; }
      set {
        body_ = value;
        bodyCase_ = value == null ? BodyOneofCase.None : BodyOneofCase.ChatEvt;
      }
    }

    private object body_;
    /// <summary>Enum of possible cases for the "body" oneof.</summary>
    public enum BodyOneofCase {
      None = 0,
      LoginReq = 100,
      LoginRes = 101,
      HsReq = 110,
      HsRes = 111,
      ChatEvt = 200,
    }
    private BodyOneofCase bodyCase_ = BodyOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BodyOneofCase BodyCase {
      get { return bodyCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBody() {
      bodyCase_ = BodyOneofCase.None;
      body_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Envelope);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Envelope other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ReqId != other.ReqId) return false;
      if (Ts != other.Ts) return false;
      if (Ver != other.Ver) return false;
      if (!object.Equals(Result, other.Result)) return false;
      if (!object.Equals(LoginReq, other.LoginReq)) return false;
      if (!object.Equals(LoginRes, other.LoginRes)) return false;
      if (!object.Equals(HsReq, other.HsReq)) return false;
      if (!object.Equals(HsRes, other.HsRes)) return false;
      if (!object.Equals(ChatEvt, other.ChatEvt)) return false;
      if (BodyCase != other.BodyCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ReqId != 0UL) hash ^= ReqId.GetHashCode();
      if (Ts != 0UL) hash ^= Ts.GetHashCode();
      if (Ver != 0) hash ^= Ver.GetHashCode();
      if (result_ != null) hash ^= Result.GetHashCode();
      if (bodyCase_ == BodyOneofCase.LoginReq) hash ^= LoginReq.GetHashCode();
      if (bodyCase_ == BodyOneofCase.LoginRes) hash ^= LoginRes.GetHashCode();
      if (bodyCase_ == BodyOneofCase.HsReq) hash ^= HsReq.GetHashCode();
      if (bodyCase_ == BodyOneofCase.HsRes) hash ^= HsRes.GetHashCode();
      if (bodyCase_ == BodyOneofCase.ChatEvt) hash ^= ChatEvt.GetHashCode();
      hash ^= (int) bodyCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ReqId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ReqId);
      }
      if (Ts != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Ts);
      }
      if (Ver != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Ver);
      }
      if (result_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(Result);
      }
      if (bodyCase_ == BodyOneofCase.LoginReq) {
        output.WriteRawTag(162, 6);
        output.WriteMessage(LoginReq);
      }
      if (bodyCase_ == BodyOneofCase.LoginRes) {
        output.WriteRawTag(170, 6);
        output.WriteMessage(LoginRes);
      }
      if (bodyCase_ == BodyOneofCase.HsReq) {
        output.WriteRawTag(242, 6);
        output.WriteMessage(HsReq);
      }
      if (bodyCase_ == BodyOneofCase.HsRes) {
        output.WriteRawTag(250, 6);
        output.WriteMessage(HsRes);
      }
      if (bodyCase_ == BodyOneofCase.ChatEvt) {
        output.WriteRawTag(194, 12);
        output.WriteMessage(ChatEvt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ReqId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ReqId);
      }
      if (Ts != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Ts);
      }
      if (Ver != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Ver);
      }
      if (result_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(Result);
      }
      if (bodyCase_ == BodyOneofCase.LoginReq) {
        output.WriteRawTag(162, 6);
        output.WriteMessage(LoginReq);
      }
      if (bodyCase_ == BodyOneofCase.LoginRes) {
        output.WriteRawTag(170, 6);
        output.WriteMessage(LoginRes);
      }
      if (bodyCase_ == BodyOneofCase.HsReq) {
        output.WriteRawTag(242, 6);
        output.WriteMessage(HsReq);
      }
      if (bodyCase_ == BodyOneofCase.HsRes) {
        output.WriteRawTag(250, 6);
        output.WriteMessage(HsRes);
      }
      if (bodyCase_ == BodyOneofCase.ChatEvt) {
        output.WriteRawTag(194, 12);
        output.WriteMessage(ChatEvt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ReqId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ReqId);
      }
      if (Ts != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Ts);
      }
      if (Ver != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Ver);
      }
      if (result_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Result);
      }
      if (bodyCase_ == BodyOneofCase.LoginReq) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(LoginReq);
      }
      if (bodyCase_ == BodyOneofCase.LoginRes) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(LoginRes);
      }
      if (bodyCase_ == BodyOneofCase.HsReq) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(HsReq);
      }
      if (bodyCase_ == BodyOneofCase.HsRes) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(HsRes);
      }
      if (bodyCase_ == BodyOneofCase.ChatEvt) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(ChatEvt);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Envelope other) {
      if (other == null) {
        return;
      }
      if (other.ReqId != 0UL) {
        ReqId = other.ReqId;
      }
      if (other.Ts != 0UL) {
        Ts = other.Ts;
      }
      if (other.Ver != 0) {
        Ver = other.Ver;
      }
      if (other.result_ != null) {
        if (result_ == null) {
          Result = new global::GamePackets.ErrorInfo();
        }
        Result.MergeFrom(other.Result);
      }
      switch (other.BodyCase) {
        case BodyOneofCase.LoginReq:
          if (LoginReq == null) {
            LoginReq = new global::GamePackets.Auth.LoginReq();
          }
          LoginReq.MergeFrom(other.LoginReq);
          break;
        case BodyOneofCase.LoginRes:
          if (LoginRes == null) {
            LoginRes = new global::GamePackets.Auth.LoginRes();
          }
          LoginRes.MergeFrom(other.LoginRes);
          break;
        case BodyOneofCase.HsReq:
          if (HsReq == null) {
            HsReq = new global::GamePackets.Auth.HandshakeReq();
          }
          HsReq.MergeFrom(other.HsReq);
          break;
        case BodyOneofCase.HsRes:
          if (HsRes == null) {
            HsRes = new global::GamePackets.Auth.HandshakeRes();
          }
          HsRes.MergeFrom(other.HsRes);
          break;
        case BodyOneofCase.ChatEvt:
          if (ChatEvt == null) {
            ChatEvt = new global::GamePackets.Chat.ChatMsg();
          }
          ChatEvt.MergeFrom(other.ChatEvt);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ReqId = input.ReadUInt64();
            break;
          }
          case 16: {
            Ts = input.ReadUInt64();
            break;
          }
          case 24: {
            Ver = input.ReadUInt32();
            break;
          }
          case 82: {
            if (result_ == null) {
              Result = new global::GamePackets.ErrorInfo();
            }
            input.ReadMessage(Result);
            break;
          }
          case 802: {
            global::GamePackets.Auth.LoginReq subBuilder = new global::GamePackets.Auth.LoginReq();
            if (bodyCase_ == BodyOneofCase.LoginReq) {
              subBuilder.MergeFrom(LoginReq);
            }
            input.ReadMessage(subBuilder);
            LoginReq = subBuilder;
            break;
          }
          case 810: {
            global::GamePackets.Auth.LoginRes subBuilder = new global::GamePackets.Auth.LoginRes();
            if (bodyCase_ == BodyOneofCase.LoginRes) {
              subBuilder.MergeFrom(LoginRes);
            }
            input.ReadMessage(subBuilder);
            LoginRes = subBuilder;
            break;
          }
          case 882: {
            global::GamePackets.Auth.HandshakeReq subBuilder = new global::GamePackets.Auth.HandshakeReq();
            if (bodyCase_ == BodyOneofCase.HsReq) {
              subBuilder.MergeFrom(HsReq);
            }
            input.ReadMessage(subBuilder);
            HsReq = subBuilder;
            break;
          }
          case 890: {
            global::GamePackets.Auth.HandshakeRes subBuilder = new global::GamePackets.Auth.HandshakeRes();
            if (bodyCase_ == BodyOneofCase.HsRes) {
              subBuilder.MergeFrom(HsRes);
            }
            input.ReadMessage(subBuilder);
            HsRes = subBuilder;
            break;
          }
          case 1602: {
            global::GamePackets.Chat.ChatMsg subBuilder = new global::GamePackets.Chat.ChatMsg();
            if (bodyCase_ == BodyOneofCase.ChatEvt) {
              subBuilder.MergeFrom(ChatEvt);
            }
            input.ReadMessage(subBuilder);
            ChatEvt = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ReqId = input.ReadUInt64();
            break;
          }
          case 16: {
            Ts = input.ReadUInt64();
            break;
          }
          case 24: {
            Ver = input.ReadUInt32();
            break;
          }
          case 82: {
            if (result_ == null) {
              Result = new global::GamePackets.ErrorInfo();
            }
            input.ReadMessage(Result);
            break;
          }
          case 802: {
            global::GamePackets.Auth.LoginReq subBuilder = new global::GamePackets.Auth.LoginReq();
            if (bodyCase_ == BodyOneofCase.LoginReq) {
              subBuilder.MergeFrom(LoginReq);
            }
            input.ReadMessage(subBuilder);
            LoginReq = subBuilder;
            break;
          }
          case 810: {
            global::GamePackets.Auth.LoginRes subBuilder = new global::GamePackets.Auth.LoginRes();
            if (bodyCase_ == BodyOneofCase.LoginRes) {
              subBuilder.MergeFrom(LoginRes);
            }
            input.ReadMessage(subBuilder);
            LoginRes = subBuilder;
            break;
          }
          case 882: {
            global::GamePackets.Auth.HandshakeReq subBuilder = new global::GamePackets.Auth.HandshakeReq();
            if (bodyCase_ == BodyOneofCase.HsReq) {
              subBuilder.MergeFrom(HsReq);
            }
            input.ReadMessage(subBuilder);
            HsReq = subBuilder;
            break;
          }
          case 890: {
            global::GamePackets.Auth.HandshakeRes subBuilder = new global::GamePackets.Auth.HandshakeRes();
            if (bodyCase_ == BodyOneofCase.HsRes) {
              subBuilder.MergeFrom(HsRes);
            }
            input.ReadMessage(subBuilder);
            HsRes = subBuilder;
            break;
          }
          case 1602: {
            global::GamePackets.Chat.ChatMsg subBuilder = new global::GamePackets.Chat.ChatMsg();
            if (bodyCase_ == BodyOneofCase.ChatEvt) {
              subBuilder.MergeFrom(ChatEvt);
            }
            input.ReadMessage(subBuilder);
            ChatEvt = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
